export const DAO_LOAN_APPROVAL = 2 * 24 * 60 * 60; // Two days
export const DAO_MILESTONE_APPROVAL = 24 * 60 * 60; // One day
export const VESTING_TIME_INTERVAL = 30 * 24 * 60 * 60; // One month
export const VESTING_BATCHES = 4; // vesting batches : 4
export const BASE_AMOUNT = 10; // 10 tokens
export const MINIMUM_INTEREST_PERCENTAGE = 20; // 20% minimum interest
export const MAX_MILESTONES = 4; // max milestones : 4
export const MILESTONE_EXTENSION = 15 * 24 * 60 * 60; // Half month
export const ONE_DAY = 24 * 60 * 60; // ONE DAY
export const AMOUNT_FOR_DAO_MEMBERSHIP = 10000; // 10000 tokens
export const FUNDING_TIME_INTERVAL = 15 * 24 * 60 * 60; // Half month
