/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import BN from "bn.js";
import { EventData, PastEventOptions } from "web3-eth-contract";

export interface EscrowDetailsContract
  extends Truffle.Contract<EscrowDetailsInstance> {
  "new"(meta?: Truffle.TransactionDetails): Promise<EscrowDetailsInstance>;
}

type AllEvents = never;

export interface EscrowDetailsInstance extends Truffle.ContractInstance {
  lendingToken(txDetails?: Truffle.TransactionDetails): Promise<string>;

  loanBorrower(
    arg0: number | BN | string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<string>;

  loanNFT(txDetails?: Truffle.TransactionDetails): Promise<string>;

  mainNFT(txDetails?: Truffle.TransactionDetails): Promise<string>;

  registry(txDetails?: Truffle.TransactionDetails): Promise<string>;

  methods: {
    lendingToken(txDetails?: Truffle.TransactionDetails): Promise<string>;

    loanBorrower(
      arg0: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;

    loanNFT(txDetails?: Truffle.TransactionDetails): Promise<string>;

    mainNFT(txDetails?: Truffle.TransactionDetails): Promise<string>;

    registry(txDetails?: Truffle.TransactionDetails): Promise<string>;
  };

  getPastEvents(event: string): Promise<EventData[]>;
  getPastEvents(
    event: string,
    options: PastEventOptions,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
  getPastEvents(event: string, options: PastEventOptions): Promise<EventData[]>;
  getPastEvents(
    event: string,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
}
