/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { AccessControlContract } from "./AccessControl";
import { OwnableContract } from "./Ownable";
import { ERC165Contract } from "./ERC165";
import { IERC165Contract } from "./IERC165";
import { ERC20PresetMinterPauserContract } from "./ERC20PresetMinterPauser";
import { ERC1155Contract } from "./ERC1155";
import { ERC1155BurnableContract } from "./ERC1155Burnable";
import { ERC1155HolderContract } from "./ERC1155Holder";
import { ERC1155ReceiverContract } from "./ERC1155Receiver";
import { IERC1155Contract } from "./IERC1155";
import { IERC1155MetadataURIContract } from "./IERC1155MetadataURI";
import { IERC1155ReceiverContract } from "./IERC1155Receiver";
import { ERC20Contract } from "./ERC20";
import { ERC20BurnableContract } from "./ERC20Burnable";
import { ERC20PausableContract } from "./ERC20Pausable";
import { IERC20Contract } from "./IERC20";
import { ERC721Contract } from "./ERC721";
import { IERC721Contract } from "./IERC721";
import { IERC721EnumerableContract } from "./IERC721Enumerable";
import { IERC721MetadataContract } from "./IERC721Metadata";
import { IERC721ReceiverContract } from "./IERC721Receiver";
import { PausableContract } from "./Pausable";
import { EscrowContract } from "./Escrow";
import { EscrowDetailsContract } from "./EscrowDetails";
import { GovernanceContract } from "./Governance";
import { IERC1155MintContract } from "./IERC1155Mint";
import { IERC721MintContract } from "./IERC721Mint";
import { IEscrowContract } from "./IEscrow";
import { IGovernanceContract } from "./IGovernance";
import { IRegistryContract } from "./IRegistry";
import { ALBTContract } from "./ALBT";
import { CollateralTokenContract } from "./CollateralToken";
import { LendingTokenContract } from "./LendingToken";
import { LoanNFTContract } from "./LoanNFT";
import { MainNFTContract } from "./MainNFT";
import { RegistryContract } from "./Registry";
import { LoanDetailsContract } from "./LoanDetails";
import { PersonalLoanContract } from "./PersonalLoan";
import { ProjectLoanContract } from "./ProjectLoan";
import { StorageContract } from "./Storage";
import { LPTokenWrapperContract } from "./LPTokenWrapper";
import { RewardDistributionRecipientContract } from "./RewardDistributionRecipient";
import { StakingContract } from "./Staking";

declare global {
  namespace Truffle {
    interface Artifacts {
      require(name: "AccessControl"): AccessControlContract;
      require(name: "Ownable"): OwnableContract;
      require(name: "ERC165"): ERC165Contract;
      require(name: "IERC165"): IERC165Contract;
      require(name: "ERC20PresetMinterPauser"): ERC20PresetMinterPauserContract;
      require(name: "ERC1155"): ERC1155Contract;
      require(name: "ERC1155Burnable"): ERC1155BurnableContract;
      require(name: "ERC1155Holder"): ERC1155HolderContract;
      require(name: "ERC1155Receiver"): ERC1155ReceiverContract;
      require(name: "IERC1155"): IERC1155Contract;
      require(name: "IERC1155MetadataURI"): IERC1155MetadataURIContract;
      require(name: "IERC1155Receiver"): IERC1155ReceiverContract;
      require(name: "ERC20"): ERC20Contract;
      require(name: "ERC20Burnable"): ERC20BurnableContract;
      require(name: "ERC20Pausable"): ERC20PausableContract;
      require(name: "IERC20"): IERC20Contract;
      require(name: "ERC721"): ERC721Contract;
      require(name: "IERC721"): IERC721Contract;
      require(name: "IERC721Enumerable"): IERC721EnumerableContract;
      require(name: "IERC721Metadata"): IERC721MetadataContract;
      require(name: "IERC721Receiver"): IERC721ReceiverContract;
      require(name: "Pausable"): PausableContract;
      require(name: "Escrow"): EscrowContract;
      require(name: "EscrowDetails"): EscrowDetailsContract;
      require(name: "Governance"): GovernanceContract;
      require(name: "IERC1155Mint"): IERC1155MintContract;
      require(name: "IERC721Mint"): IERC721MintContract;
      require(name: "IEscrow"): IEscrowContract;
      require(name: "IGovernance"): IGovernanceContract;
      require(name: "IRegistry"): IRegistryContract;
      require(name: "ALBT"): ALBTContract;
      require(name: "CollateralToken"): CollateralTokenContract;
      require(name: "LendingToken"): LendingTokenContract;
      require(name: "LoanNFT"): LoanNFTContract;
      require(name: "MainNFT"): MainNFTContract;
      require(name: "Registry"): RegistryContract;
      require(name: "LoanDetails"): LoanDetailsContract;
      require(name: "PersonalLoan"): PersonalLoanContract;
      require(name: "ProjectLoan"): ProjectLoanContract;
      require(name: "Storage"): StorageContract;
      require(name: "LPTokenWrapper"): LPTokenWrapperContract;
      require(
        name: "RewardDistributionRecipient"
      ): RewardDistributionRecipientContract;
      require(name: "Staking"): StakingContract;
    }
  }
}

export { AccessControlContract, AccessControlInstance } from "./AccessControl";
export { OwnableContract, OwnableInstance } from "./Ownable";
export { ERC165Contract, ERC165Instance } from "./ERC165";
export { IERC165Contract, IERC165Instance } from "./IERC165";
export {
  ERC20PresetMinterPauserContract,
  ERC20PresetMinterPauserInstance,
} from "./ERC20PresetMinterPauser";
export { ERC1155Contract, ERC1155Instance } from "./ERC1155";
export {
  ERC1155BurnableContract,
  ERC1155BurnableInstance,
} from "./ERC1155Burnable";
export { ERC1155HolderContract, ERC1155HolderInstance } from "./ERC1155Holder";
export {
  ERC1155ReceiverContract,
  ERC1155ReceiverInstance,
} from "./ERC1155Receiver";
export { IERC1155Contract, IERC1155Instance } from "./IERC1155";
export {
  IERC1155MetadataURIContract,
  IERC1155MetadataURIInstance,
} from "./IERC1155MetadataURI";
export {
  IERC1155ReceiverContract,
  IERC1155ReceiverInstance,
} from "./IERC1155Receiver";
export { ERC20Contract, ERC20Instance } from "./ERC20";
export { ERC20BurnableContract, ERC20BurnableInstance } from "./ERC20Burnable";
export { ERC20PausableContract, ERC20PausableInstance } from "./ERC20Pausable";
export { IERC20Contract, IERC20Instance } from "./IERC20";
export { ERC721Contract, ERC721Instance } from "./ERC721";
export { IERC721Contract, IERC721Instance } from "./IERC721";
export {
  IERC721EnumerableContract,
  IERC721EnumerableInstance,
} from "./IERC721Enumerable";
export {
  IERC721MetadataContract,
  IERC721MetadataInstance,
} from "./IERC721Metadata";
export {
  IERC721ReceiverContract,
  IERC721ReceiverInstance,
} from "./IERC721Receiver";
export { PausableContract, PausableInstance } from "./Pausable";
export { EscrowContract, EscrowInstance } from "./Escrow";
export { EscrowDetailsContract, EscrowDetailsInstance } from "./EscrowDetails";
export { GovernanceContract, GovernanceInstance } from "./Governance";
export { IERC1155MintContract, IERC1155MintInstance } from "./IERC1155Mint";
export { IERC721MintContract, IERC721MintInstance } from "./IERC721Mint";
export { IEscrowContract, IEscrowInstance } from "./IEscrow";
export { IGovernanceContract, IGovernanceInstance } from "./IGovernance";
export { IRegistryContract, IRegistryInstance } from "./IRegistry";
export { ALBTContract, ALBTInstance } from "./ALBT";
export {
  CollateralTokenContract,
  CollateralTokenInstance,
} from "./CollateralToken";
export { LendingTokenContract, LendingTokenInstance } from "./LendingToken";
export { LoanNFTContract, LoanNFTInstance } from "./LoanNFT";
export { MainNFTContract, MainNFTInstance } from "./MainNFT";
export { RegistryContract, RegistryInstance } from "./Registry";
export { LoanDetailsContract, LoanDetailsInstance } from "./LoanDetails";
export { PersonalLoanContract, PersonalLoanInstance } from "./PersonalLoan";
export { ProjectLoanContract, ProjectLoanInstance } from "./ProjectLoan";
export { StorageContract, StorageInstance } from "./Storage";
export {
  LPTokenWrapperContract,
  LPTokenWrapperInstance,
} from "./LPTokenWrapper";
export {
  RewardDistributionRecipientContract,
  RewardDistributionRecipientInstance,
} from "./RewardDistributionRecipient";
export { StakingContract, StakingInstance } from "./Staking";
